<?php

namespace cfd\doc;
use common\base_models\kds\Teacher;

/**
 * Created by PhpStorm.
 * User: chatfeed
 * Date: 2018/1/5
 * Time: 下午1:55
 */
class Module extends \yii\base\Module {

    public $modelDescriptions=[];
    public $modelsMap=[];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->modelDescriptions)){
            $this->modelDescriptions = require __DIR__.'/config/ModelDescription.php';
        }
    }
}